[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

board_microros_distro = jazzy
board_microros_transport = wifi

build_flags = 
    -D MICROROS_IN_PLATFORMIO

lib_deps =
    https://github.com/micro-ROS/micro_ros_platformio
    pololu/VL53L0X@^1.3.1
    adafruit/Adafruit BusIO@^1.14.1
	madhephaestus/ESP32Servo@^3.0.0

board_build.partitions = default.csv

monitor_speed = 115200
monitor_filters = esp32_exception_decoder